                                <option value=''>--</option>
                                <option value="Argentina">Argentina</option>
                                <option value="Bahamas">Bahamas</option>
                                <option value="Barbados">Barbados</option>
                                <option value="Belice">Belice</option>
                                <option value="Bolivia">Bolivia</option>
                                <option value="Brasil">Brasil</option>
                                <option value="Canadá">Canadá</option>
                                <option value="Chile">Chile</option>
                                <option value="Colombia">Colombia</option>
                                <option value="Costa-Rica">Costa Rica</option>
                                <option value="Cuba">Cuba</option>
                                <option value="Dominica">Dominica</option>
                                <option value="Ecuador">Ecuador</option>
                                <option value="El-Salvador">El salvador</option>
                                <option value="España">España</option>
                                <option value="Estados-Unidos">Estados Unidos</option>
                                <option value="Granada">Granada</option>
                                <option value="Guatemala">Guatemala</option>
                                <option value="Haití">Haití</option>
                                <option value="Honduras">Honduras</option>
                                <option value="Jamaica">Jamaica</option>
                                <option value="México">México</option>
                                <option value="Argentina">Argenina</option>
                                <option value="Bahamas">Bahamas</option>
                                <option value="Barbados">Barbados</option>
                                <option value="Belice">Belice</option>
                                <option value="Nicaragua">Nicaragua</option>
                                <option value="Panamá">Panamá</option>
                                <option value="Paraguay">Paraguay</option>
                                <option value="Perú">Perú</option>
                                <option value="República-Dominicana">República Dominicana</option>
                                <option value="Trinidad-y-Tobago">Trinidad y Tobago</option>
                                <option value="Venezuela">Venezuela</option>
                                